name = "GRAD Telephone"
prefix = "grad_telephone"
author = "nomisum"
files = [
    "mod.cpp",
    "logo_active_ca.paa",
    "logo_ca.paa",
    "overview_co.paa",
    "logo_small_ca.paa"
    "LICENSE",
    "README.md"
]

key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip _{{semver.major}}.{{semver.minor}}.{{semver.patch}}.{{semver.build}}"
]

[header_exts]
version= "{{git \"id 8\"}}"
